---
# tasks file for clickhouse-role
- name: get clickhouse
  ansible.builtin.get_url:
    url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
    dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
  with_items: "{{ clickhouse_packages }}"
- name: install clickhouse packages
  become: true
  ansible.builtin.apt:
    name:
      - clickhouse-common-static-{{ clickhouse_version }}.rpm
      - clickhouse-client-{{ clickhouse_version }}.rpm
      - clickhouse-server-{{ clickhouse_version }}.rpm
  notify: Start clickhouse service
- name: flash handlers
  ansible.builtin.meta: flush_handlers
- name: pause for 10 second for start servises
  pause:
    seconds: 10
- name: create database
  ansible.builtin.command: "clickhouse-client -h 127.0.0.1 -q 'create database logs;'"
  register: create_db
  failed_when: create_db.rc != 0 and create_db.rc !=82
  changed_when: create_db.rc == 0
- name: create table
  ansible.builtin.command: "clickhouse-client -h 127.0.0.1 -q 'CREATE TABLE IF NOT EXISTS  logs.access_logs ( message String ) ENGINE = MergeTree() ORDER BY tuple()'"
  register: create_table
  failed_when: create_table.rc != 0 and create_table.rc !=82
  changed_when: create_table.rc == 0
- name: create general config
  become: true
  ansible.builtin.template:
    src: templates/config.xml.j2
    dest: /etc/clickhouse-server/config.xml
    mode: 0644
  notify: Start clickhouse service
